---
- name: Check and update sudo package on RHEL hosts for CVE-2025-32462 and CVE-2025-32463
  hosts: all
  become: yes
  vars:
    fixed_sudo_version: "1.9.17p1"
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: dnf

    - name: Check current sudo version
      ansible.builtin.command: rpm -q sudo
      register: sudo_version_check
      changed_when: false

    - name: Set sudo version fact
      ansible.builtin.set_fact:
        sudo_version: "{{ sudo_version_check.stdout | regex_replace('sudo-', '') | regex_replace('\\.el[0-9].*', '') }}"

    - name: Check if sudo version is vulnerable to CVE-2025-32462
      ansible.builtin.set_fact:
        cve_2025_32462_vulnerable: "{{ sudo_version is version('1.8.8', '>=') and sudo_version is version('1.9.17', '<=') }}"

    - name: Check if sudo version is vulnerable to CVE-2025-32463
      ansible.builtin.set_fact:
        cve_2025_32463_vulnerable: "{{ sudo_version is version('1.9.14', '>=') and sudo_version is version('1.9.17', '<=') }}"

    - name: Determine if update is needed
      ansible.builtin.set_fact:
        is_vulnerable: "{{ cve_2025_32462_vulnerable or cve_2025_32463_vulnerable }}"

    - name: Report current sudo version and CVE status
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Current sudo version: {{ sudo_version }}"
          - "CVE-2025-32462: {{ 'Vulnerable' if cve_2025_32462_vulnerable else 'Not Vulnerable' }}"
          - "CVE-2025-32463: {{ 'Vulnerable' if cve_2025_32463_vulnerable else 'Not Vulnerable' }}"
          - "Action required: {{ 'Update to sudo-1.9.17p1 or later' if is_vulnerable else 'No action needed' }}"

    - name: Update sudo package if vulnerable
      ansible.builtin.dnf:
        name: sudo
        state: latest
      when: is_vulnerable
      register: sudo_update

    - name: Re-check sudo version after update
      ansible.builtin.command: rpm -q sudo
      register: sudo_version_post_update
      changed_when: false
      when: sudo_update.changed

    - name: Report sudo version after update
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} updated to sudo version {{ sudo_version_post_update.stdout | regex_replace('sudo-', '') | regex_replace('\\.el[0-9].*', '') }}"
      when: sudo_update.changed

    - name: Print report to stdout
      ansible.builtin.debug:
        msg: |
          Sudo CVE Report for {{ inventory_hostname }}
          ---------------------------------------
          Initial sudo version: {{ sudo_version }}
          CVE-2025-32462: {{ 'Vulnerable' if cve_2025_32462_vulnerable else 'Not Vulnerable' }}
          CVE-2025-32463: {{ 'Vulnerable' if cve_2025_32463_vulnerable else 'Not Vulnerable' }}
          Updated: {{ 'Yes' if sudo_update.changed else 'No' }}
          {% if sudo_update.changed %}
          New sudo version: {{ sudo_version_post_update.stdout | regex_replace('sudo-', '') | regex_replace('\\.el[0-9].*', '') }}
          {% endif %}
          ---------------------------------------
